apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterIP.name }}
spec:
  selector:
    app: {{ .Values.webapp.name }}
    app: {{ .Values.nginx.name }}
  ports:
  - name: http
    port: {{ .Values.clusterIP.port }}
    targetPort: {{ .Values.clusterIP.targetPort }}
  type: {{ .Values.clusterIP.type }}