apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lb.name }}
spec:
  type: {{ .Values.type }}
  selector:
    app: {{ .Values.webapp.name }}
  ports:
  - name: http
    port: 80
    targetPort: 4444