apiVersion: v1
kind: Service
metadata:
  name: nrich-webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: nrich-pod
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 4444
    targetPort: 4444