apiVersion: v1
kind: Pod
metadata:
  name: nrich-webapp
  labels:
      app: nrich-webapp
spec:
  containers:
  - name: nrich-webapp
    image: eu.gcr.io/nrich-terraform/nrich-webapp
    imagePullPolicy: "Always"
    ports:
    - containerPort: 4444