apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nrich-html
     command: ["/bin/bash"]
    args:
    - "-c"
    - while true; do
        echo -en '\n';
        printenv CONTAINER_NAME POD_IP CLUSTER_NAME;
        export CONTAINER_NAME=$CONTAINER_NAME;
        export POD_IP=$POD_IP;
        export CLUSTER_NAME=$CLUSTER_NAME;
        envsubst < /usr/share/nginx/html/index.html > /usr/share/nginx/html/index.html.tmp && mv /usr/share/nginx/html/index.html.tmp /usr/share/nginx/html/index.html;
        nginx;
        sleep 10;
      done;  
    env:
    - name: CONTAINER_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CLUSTER_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    imagePullPolicy: "IfNotPresent"
    ports:
    - containerPort: 80