# values.yaml
webapp:
  name: nrich-webapp
  image: nrich-webapp
  
  nginx:
    name: nrich-nginx
    image: nrich-nginx

repository: eu.gcr.io/nrich-terraform

lb:
  name: nrich-webapp-lb
  type: LoadBalancer

ingress:
  name: nrich-webapp-ingress
  host: nrich-webapp
  target: /coin
  path: /coin


clusterIP:
  name: nrich-webapp-clusterip
  type: ClusterIP
  port: 80
  targetPort: 4444