image:
  name: nginx
  namespace: nginx-namespace
  repository: eu.gcr.io/nrich-terraform/nrich-html
  tag: latest
  pullPolicy: Always
  containerPort: 80

service:
  name: nginx-loadbalancer
  namespace: nginx-namespace
  selector:
    app: nginx
  ports:
    name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

ingress:
  host: nginx
  name: nginx-ingress
  namespace: nginx-namespace
  path: /
  targetPort: 80