apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nrich-html
    volumeMounts:
      - name: script-volume
        mountPath: /usr/share/nginx/html
    command: [ "/bin/bash", "-c", "chmod +x /usr/share/nginx/html/replace-env.sh && /usr/share/nginx/html/replace-env.sh" ]
    env:
    - name: CONTAINER_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CLUSTER_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    imagePullPolicy: "IfNotPresent"
    ports:
    - containerPort: 80
  volumes:
  - name: script-volume
    configMap:
      name: configmap
      items:
      - key: edit-html.sh
        path: html/edit-html.sh
