apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.image.name }}
spec:
  containers:
  - name: {{ .Values.image.name }}
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    command: [ "/bin/bash", "-c", "sh /opt/edit-html.sh && nginx -g 'daemon off;'"]
    env:
    - name: CONTAINER_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CLUSTER_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
    - containerPort: {{ .Values.containerPort }}